/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        ArrayList<Integer> arr = new ArrayList<>();

        for(int i = 0; i < 10; i++) {
            arr.add((int)(Math.random()*100));
        }

        printArr(arr);
        arr = myDemoFunction(arr, 2, 'a');
        printArr(arr);
        
    }

    //adds the given value to the given place
    public static ArrayList<Integer> myDemoFunction(ArrayList<Integer> arr, int place, int value) {
       
        arr.add(value);
       
        if(place > arr.size())
            System.out.println("The given place is bigger than size.");
        
        else if(place < 0)
            System.out.println("The given place does not exists.");

        else {

            for(int i = arr.size() - 1; i > place; i--) {
                int tmp = arr.get(i);
                arr.set(i, arr.get(i - 1));
                arr.set(i - 1, tmp);
            }

        }

        return arr;
    }

    public static void printArr(ArrayList<Integer> arr) {
        for(int i = 0; i < arr.size(); i++) {
            System.out.print(arr.get(i) + " ");
        }
        System.out.println();
    }

}
